/*!
 * drag.js
 * Date: 2013-12-06
 * (c) 2009-2013 TangBin, http://www.planeArt.cn
 *
 * This is licensed under the GNU LGPL, version 2.1 or later.
 * For details, see: http://www.gnu.org/licenses/lgpl-2.1.html
 */

define(["require","jquery"],function(e){var t=e("jquery"),n=t(window),r=t(document),i="createTouch"in document,s=document.documentElement,o=!("minWidth"in s.style),u=!o&&"onlosecapture"in s,a="setCapture"in s,f={start:i?"touchstart":"mousedown",over:i?"touchmove":"mousemove",end:i?"touchend":"mouseup"},l=i?function(e){return e.touches||(e=e.originalEvent.touches.item(0)),e}:function(e){return e},c=function(){this.start=t.proxy(this.start,this),this.over=t.proxy(this.over,this),this.end=t.proxy(this.end,this),this.onstart=this.onover=this.onend=t.noop};return c.types=f,c.prototype={start:function(e){return e=this.startFix(e),r.on(f.over,this.over).on(f.end,this.end),this.onstart(e),!1},over:function(e){return e=this.overFix(e),this.onover(e),!1},end:function(e){return e=this.endFix(e),r.off(f.over,this.over).off(f.end,this.end),this.onend(e),!1},startFix:function(e){return e=l(e),this.target=t(e.target),this.selectstart=function(){return!1},r.on("selectstart",this.selectstart).on("dblclick",this.end),u?this.target.on("losecapture",this.end):n.on("blur",this.end),a&&this.target[0].setCapture(),e},overFix:function(e){return e=l(e),e},endFix:function(e){return e=l(e),r.off("selectstart",this.selectstart).off("dblclick",this.end),u?this.target.off("losecapture",this.end):n.off("blur",this.end),a&&this.target[0].releaseCapture(),e}},c.create=function(e,i){var s=t(e),o=new c,u=c.types.start,a=function(){},f=e.className.replace(/^\s|\s.*/g,"")+"-drag-start",l,h,p,d,v={onstart:a,onover:a,onend:a,off:function(){s.off(u,o.start)}};return o.onstart=function(t){var i=s.css("position")==="fixed",o=r.scrollLeft(),u=r.scrollTop(),a=s.width(),c=s.height();l=0,h=0,p=i?n.width()-a+l:r.width()-a,d=i?n.height()-c+h:r.height()-c;var m=s.offset(),g=this.startLeft=i?m.left-o:m.left,y=this.startTop=i?m.top-u:m.top;this.clientX=t.clientX,this.clientY=t.clientY,s.addClass(f),v.onstart.call(e,t,g,y)},o.onover=function(t){var n=t.clientX-this.clientX+this.startLeft,r=t.clientY-this.clientY+this.startTop,i=s[0].style;n=Math.max(l,Math.min(p,n)),r=Math.max(h,Math.min(d,r)),i.left=n+"px",i.top=r+"px",v.onover.call(e,t,n,r)},o.onend=function(t){var n=s.position(),r=n.left,i=n.top;s.removeClass(f),v.onend.call(e,t,r,i)},o.off=function(){s.off(u,o.start)},i?o.start(i):s.on(u,o.start),v},c});